import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import SearchIcon from '@mui/icons-material/Search';
import Navbar from '../components/Navbar';
import { useUser } from '../firebase/useUser';
import Topic from '../components/Topic';
import Image from 'next/image';
import db from '../firebase/initFirebase';
import { Article } from '../components/Article';
// import Banner from '../public/banner.png';

const home = () => {
  const date = new Date().getHours();
  const greeting = date < 12 ? 'Morning' : date < 18 ? 'Afternoon' : 'Evening';
  const { user, logout } = useUser();
  const [news, setNews] = useState();

  const handleSubmit = async (e) => {
    e.preventDefault();
    const colRef = collections(db, 'topics');
    await addDoc(colRef, {})
    const searchValue = search.value;
    const searchResult = await db
      .collection('topics')
      .where('title', '==', searchValue)
      .get();
    console.log(searchResult);
  }

  useEffect(() => {
    fetch('https://newsapi.org/v2/top-headlines?country=us&apiKey=53f7eb5c4a0b4b5f9ba183efb9aa1fd6')
      .then((response) => response.json())
      .then((data) => setNews(data.articles));
  }, [])

  console.log(news);
  const Topics = [
    'Sports',
    'Politics',
    'Entertainment',
    'Technology',
    'Science',
    'Health',
    'Business',
    'World',
  ]

  if (user) {
    return (
      <div className='container mx-auto'>
        <Head>
          <title>Digest</title>
          <meta name='digest' content='Generated by create next app' />
          <link rel='icon' href='./public/favicon.ico' />
        </Head>
        <Navbar />
        <div className='mx-32 flex flex-col'>
          <div className='sticky top-0 mb-10 bg-white py-5'>
            <h1 className='left-0 text-4xl font-bold'>{greeting} {user.name}</h1>
            {/* <div className='relative right-20 border p-1 rounded-lg'>
              <SearchIcon sx={{ fontSize: 20 }} />
              <input type='text' className='bg-inherit btn ml-1' placeholder='Search' />
            </div> */}
          </div>
          <div className='flex justify-center mb-10'>
            <Image src='/banner.jpg' alt='digest' width={750} height={250} />
            {/* <h1 className='text-7xl'>...Let's Digest</h1> */}
          </div>
          <div className='sticky top-16 bg-white mb-10'>
            <h1 className='text-2xl font-bold'>Topics</h1>
            <div className='flex flex-row space-x-4 justify-center mb-5 mt-5'>
              {Topics.map((topic) => <Topic label={topic} />)}
            </div>
          </div>
          <div className='sticky top-40 mb-10 bg-white'>
            <h1 className='text-2xl font-bold'>Trending</h1>
          </div>
          <div className='grid content-evenly ml-10 mb-32'>
            {/* {news && <Article news={news} />} */}
            <h1 className='text-5xl mb-5 text-right font-bold'>{news && news[0].source.name}</h1>
            <div className="flex flex-row space-x-4">
              {news &&
                <div>
                  {news[0].urlToImage && <Image src={news[0].urlToImage} width={300} height={300} />}
                </div>
              }
              <div>
                {news && news[0].title}
              </div>
            </div>
            <h1 className='text-5xl mb-5 text-right mt-10 font-bold'>{news && news[1].source.name}</h1>
            <div className="flex flex-row space-x-4">
              {/* {news &&
                <div>
                  {news[1].urlToImage && <Image src={news[1].urlToImage} width={300} height={300} />}
                </div>
              } */}
              <div>
                {news && news[1].title}
              </div>
            </div>
            <h1 className='text-5xl mb-5 text-right mt-10 font-bold'>{news && news[2].source.name}</h1>
            <div className="flex flex-row space-x-4">
              <div>
                {news && news[2].title}
              </div>
            </div>
            <h1 className='text-5xl mb-5 text-right mt-10 font-bold'>{news && news[3].source.name}</h1>
            <div className="flex flex-row space-x-4">
              <div>
                {news && news[3].title}
              </div>
            </div>
            <h1 className='text-5xl mb-5 text-right mt-10 font-bold'>{news && news[4].source.name}</h1>
            <div className="flex flex-row space-x-4">
              <div>
                {news && news[4].title}
              </div>
            </div>
          </div>
          <div className='sticky top-5 mb-10'>
            <h1 className='text-2xl font-bold'>New</h1>
          </div>
          <div className='grid content-evenly ml-10 mb-32'>
            <h1 className='text-5xl'>[Placeholder]</h1>
          </div>
        </div>
      </div>
    );
  }
}

export default home;
