import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import SearchIcon from '@mui/icons-material/Search';
import Navbar from '../components/Navbar';
import { useUser } from '../firebase/useUser';
import Topic from '../components/Topic';
import db from '../firebase/initFirebase';

const home = () => {
  const date = new Date().getHours();
  const greeting = date < 12 ? 'Morning' : date < 18 ? 'Afternoon' : 'Evening';
  const { user, logout } = useUser();
  const [news, setNews] = useState();

  const handleSubmit = async (e) => {
    e.preventDefault();
    const colRef = collections(db, 'topics');
    await addDoc(colRef, {})
    const searchValue = search.value;
    const searchResult = await db
      .collection('topics')
      .where('title', '==', searchValue)
      .get();
    // console.log(searchResult);
  }

  useEffect(() => {
    fetch('https://newsapi.org/v2/top-headlines?country=us&apiKey=53f7eb5c4a0b4b5f9ba183efb9aa1fd6')
      .then((response) => response.json())
      .then((data) => setNews(data.articles));
  }, []);

  const Topics = [
    'Sports',
    'Politics',
    'Entertainment',
    'Technology',
    'Science',
    'Health',
    'Business',
  ];

  const [Frequency, setFrequency] = useState("");

  if (user) {
    return (
      <div className='container mx-auto'>
        <Head>
          <title>Digest</title>
          <meta name='digest' content='Generated by create next app' />
          <link rel='icon' href='./public/favicon.ico' />
        </Head>
        <Navbar />
        <div className='mx-32'>
          <div className='sticky top-0 bg-white py-5'>
            <h1 className='left-0 text-6xl font-bold'>{greeting} {user.name}</h1>
          </div>
          <div className='flex flex-row mt-2'>
            <h3 className='mr-2'>How frequent would you like your digest?</h3>
            <select onChange={e => setFrequency(e.target.value)}>
              <option value='daily'>Daily</option>
              <option value='weekly'>Weekly</option>
              <option value='monthly'>Monthly</option>
            </select>
          </div>
          <div className='flex justify-center mb-10'>
          </div>
          <div className='sticky top-20 mb-10 bg-white'>
            <h1 className='text-2xl font-bold'>Trending</h1>
          </div>
          <div className='grid content-evenly ml-10 mb-32'>
            <h1 className='text-5xl mb-5 text-right font-bold'>{news && news[0].source.name}</h1>
            <div className="flex flex-row space-x-4">
              <div>
                {news && news[0].title}
              </div>
            </div>
            <h1 className='text-5xl mb-5 text-right mt-10 font-bold'>{news && news[1].source.name}</h1>
            <div className="flex flex-row space-x-4">
              <div>
                {news && news[1].title}
              </div>
            </div>
            <h1 className='text-5xl mb-5 text-right mt-10 font-bold'>{news && news[2].source.name}</h1>
            <div className="flex flex-row space-x-4">
              <div>
                {news && news[2].title}
              </div>
            </div>
            <h1 className='text-5xl mb-5 text-right mt-10 font-bold'>{news && news[3].source.name}</h1>
            <div className="flex flex-row space-x-4">
              <div>
                {news && news[3].title}
              </div>
            </div>
            <h1 className='text-5xl mb-5 text-right mt-10 font-bold'>{news && news[4].source.name}</h1>
            <div className="flex flex-row space-x-4">
              <div>
                {news && news[4].title}
              </div>
            </div>
          </div>
          <div className='sticky top-24 bg-white mb-10'>
            <h1 className='text-2xl font-bold'>Your Topics</h1>
            <div className='flex flex-row space-x-4 justify-center mb-5 mt-5'>
              {Topics.map((topic) => <Topic label={topic} />)}
            </div>
          </div>
          {Topics.map((topic) =>
            <div className='mb-10'>
              <h1 className='text-2xl font-bold text-right'>from {topic}</h1>
            </div>
          )}
        </div>
      </div>
    );
  }
}

export default home;
