import * as React from 'react';
import Toolbar from '@mui/material/Toolbar';
import Head from 'next/head'
import List from '@mui/material/List';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import Container from '@mui/material/Container';
import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import { NextPage } from 'next';
import ListItemButton from '@mui/material/ListItemButton';
import HomeIcon from '@mui/icons-material/Home';
import SearchIcon from '@mui/icons-material/Search';
import BarChartIcon from '@mui/icons-material/BarChart';
import BugReportIcon from '@mui/icons-material/BugReport';
import AccessibilityIcon from '@mui/icons-material/Accessibility';

function Copyright(props: any) {
  return (
    <Typography variant="body2" align="center" {...props}>
      {'Copyright © '}
      {new Date().getFullYear()}
      {'.'}
    </Typography>
  );
}

const home: NextPage = () => {
  const [open, setOpen] = React.useState(true);

  return (
    <Container maxWidth="md">
      <Head>
        <title>Digest</title>
        <meta name="digest" content="Generated by create next app" />
        <link rel="icon" href="./public/favicon.ico" />
      </Head>
      <nav className='sticky top-0 backdrop-blur bg/60 mb-5'>
        <Toolbar>
          <Typography sx={{ flexGrow: 1 }} />
          <div className="border pl-2 p-1 rounded-lg bg">
            <SearchIcon />
            <input type="text" className="bg-inherit ml-2 btn" placeholder="Search" />
          </div>
          <IconButton color="inherit">
            <AccountCircleIcon sx={{ fontSize: 40 }} />
          </IconButton>
        </Toolbar>
      </nav>
      <Container className='flex flex-row relative'>
        <div className='w-32 mt-1 absolute md:fixed'>
          <List>
            <ListItemButton className='rounded-md'>
              <HomeIcon />
              <h1 className='text-md ml-3'>Home</h1>
            </ListItemButton>
            <ListItemButton className='rounded-md'>
              <SearchIcon />
              <h1 className='text-md ml-3'>Search</h1>
            </ListItemButton>
            <ListItemButton className='rounded-md'>
              <BarChartIcon />
              <h1 className='text-md ml-3'>Topics</h1>
            </ListItemButton>
            <ListItemButton className='rounded-md mt-20'>
              <BugReportIcon />
              <h1 className='text-md ml-3'>Report</h1>
            </ListItemButton>
          </List>
        </div>
        <div className='w-full md:w-10/12 ml-auto'>
          <h1 className='text-2xl font-bold ml-4'>Good [time] [username]</h1>
          <div className='flex flex-row mt-5'>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
          </div>
          <div className='flex flex-row'>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
          </div>
          <h1 className='text-2xl font-bold ml-4 mt-10'>Breaking</h1>
          <div className='flex flex-row'>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
            <div className='bg-gray-800 w-48 h-32 rounded-lg ml-4 mt-10 bg-gradient-to-r from-gray-200 via-gray-400 to-gray-600'></div>
          </div>
        </div>
      </Container>
      <Container maxWidth="lg" sx={{ mt: 4, mb: 4 }}>
        <Copyright sx={{ pt: 4 }} />
      </Container>
    </Container>
  );
}

export default home;
