import Head from 'next/head'
import { motion } from 'framer-motion'
import Container from '@mui/material/Container'
import Auth from '../components/Auth'
import Link from 'next/link';

const index = () => {
  return (
    <Container maxWidth='md'>
      <Head>
        <title>Digest</title>
        <meta name='digest' content='Generated by create next app' />
        <link rel='icon' href='./public/favicon.ico' />
      </Head>

      <main className='grid h-screen place-items-center'>
        <div>
          <motion.div
            initial={{ opacity: 0, scale: 2 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: .5 }}
          >
            <h1 className='text-7xl font-bold text-center'>
              welcome to Digest!
            </h1>
          </motion.div>
          <motion.div
            initial={{ opacity: 0, scale: 0 }}
            animate={{ opacity: 1, scale: .5 }}
            transition={{ delay: 1.5, duration: .2 }}
          >
            <Link href='/home'>
              <a>
                <h3 className='text-4xl text-right'>Let&apos;s get you started</h3>
              </a>
            </Link>
          {/* <Auth /> */}
          </motion.div>
        </div>
      </main>
    </Container>
  )
}

export default index
