import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Digest</title>
        <meta name="digest" content="Generated by create next app" />
        <link rel="icon" href="./public/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Digest!
        </h1>
      </main>
    </div>
  )
}

export default Home
