import type { NextPage } from 'next'
import Head from 'next/head'
import NavigateNextIcon from '@mui/icons-material/NavigateNext'
import Link from 'next/link'
import { motion } from 'framer-motion'
import Container from '@mui/material/Container'

const index: NextPage = () => {
  return (
    <Container maxWidth="md">
      <Head>
        <title>Digest</title>
        <meta name="digest" content="Generated by create next app" />
        <link rel="icon" href="./public/favicon.ico" />
      </Head>

      <main className='grid h-screen place-items-center'>
        <div>
          <motion.div
            initial={{ opacity: 0, scale: 2 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: .5 }}
          >
            <h1 className="text-7xl font-bold text-center">
              welcome to Digest!
            </h1>
          </motion.div>
          <motion.div
            initial={{ opacity: 0, scale: 0 }}
            animate={{ opacity: 1, scale: .5 }}
            transition={{ delay: 1.5, duration: .2 }}
          >
            <h3 className="text-4xl text-right">
              <Link href="/auth">
                <a>
                <div>Let's get you started
                  <NavigateNextIcon sx={{ fontSize: 60 }} />
                </div>
                </a>
              </Link>
            </h3>
          </motion.div>
        </div>
      </main>
    </Container>
  )
}

export default index
