import * as React from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import { useUser } from '../firebase/useUser';
// import db from '../firebase/initFirebase';
import { useState } from 'react'
import { Combobox } from '@headlessui/react'

const topics = () => {
  const { user, logout } = useUser();

  const topics = [
    'Sports',
    'Politics',
    'Entertainment',
    'Technology',
    'Science',
    'Health',
    'Business',
    'World',
    'National',
    'Politics',
    'Opinion',
    'Arts',
    'Fashion',
    'Food',
    'Travel',
    'Magazine',
    'Real Estate',
    'T Magazine',
    'Video',
  ]

  const [userTopics, setUserTopics] = useState([])
  const [selectedTopic, setSelectedTopic] = useState()
  const [query, setQuery] = useState('');

  const filteredtopics =
    query === ''
      ? topics
      : topics.filter((person) => {
        return person.toLowerCase().includes(query.toLowerCase())
      })

  const handleAdd = () => {
    userTopics.push(selectedTopic)
    setUserTopics(userTopics)
  }

  if (user) {

    return (
      <div className='container mx-auto'>
        <Head>
          <title>Digest</title>
          <meta name='digest' content='Generated by create next app' />
          <link rel='icon' href='./public/favicon.ico' />
        </Head>
        <Navbar />
        <div className='flex flex-row'>
          <div className='mr-5 mt-4'>
            <h1 className='text-5xl text-center'>Add a topic: </h1>
          </div>
          <div className='mt-5 flex flex-row'>
            <form>
              <Combobox value={selectedTopic} onChange={setSelectedTopic}>
                <Combobox.Input className="text-4xl" onChange={(event) => setQuery(event.target.value)} />
                <Combobox.Options className="text-4xl">
                  {filteredtopics.map((topic) => (
                    <Combobox.Option key={topic} value={topic}>
                      {topic}
                    </Combobox.Option>
                  ))}
                </Combobox.Options>
              </Combobox>
            </form>
          </div>
          <button
            type="submit"
            className="mt-3 inline-flex w-full justify-center rounded-md border p-2 text-xl shadow-sm sm:mt-0 sm:ml-3 sm:w-auto sm:text-md"
            onClick={handleAdd}
          >
            Add
          </button>
        </div>
      </div>
    );
  }
}

export default topics;
